name: CI

on: [push]

jobs:
  test-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - uses: browser-actions/setup-firefox@v1

      - name: Install dependencies
        run: pip install --group dev .

      - name: Run unit tests
        run: python src/manage.py test lists accounts

      - name: Run all tests
        run: cd src && python manage.py test
